services:
  nginx:
    container_name: ${PROJECT_NAME}_nginx
    image: nginx
    volumes:
      - ./etc/nginx/${ENV}/:/etc/nginx/templates/
      - ${NGINX_SSL}:/etc/ssl
      - ./${PROJECT_DIR}/:/var/www/app/
    ports:
      - ${NGINX_HTTP}:80
      - ${NGINX_HTTPS}:443
    environment:
      - NGINX_HTTP=${NGINX_HTTP}
      - NGINX_HTTPS=${NGINX_HTTPS}
      - NGINX_HOST=${NGINX_HOST}
    depends_on:
      - php
      - mysql
    restart: always
    networks:
      app:
        ipv4_address: ${NGINX_IP}

  php:
    container_name: ${PROJECT_NAME}_php
    build:
      context: etc/php/${ENV}
      args:
        ENABLE_DEBUG: ${ENABLE_DEBUG}
        XDEBUG_CLIENT_HOST: ${XDEBUG_CLIENT_HOST}
        XDEBUG_CLIENT_PORT: ${XDEBUG_CLIENT_PORT}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY}
    restart: always
    ports:
      - ${WEBPACK_DEV_PORT}:${WEBPACK_DEV_PORT}
      - ${XDEBUG_CLIENT_PORT}:${XDEBUG_CLIENT_PORT}
    volumes:
      - ./etc/php/${ENV}/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./${PROJECT_DIR}:/var/www/app
    depends_on:
      - postgres
    networks:
      app:
        ipv4_address: ${PHP_IP}

  mysql:
    container_name: ${PROJECT_NAME}_postgres
    image: mysql:${MYSQL_VERSION}
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data/db/mysql:/var/lib/mysql
      - ./log/mysql/:/var/log/mysql/
      - ./log/mysql/:/var/lib/mysql-filess
    ports:
      - ${MYSQL_PORT}:3307
    networks:
      app:
        ipv4_address: ${MYSQL_IP}

networks:
  app:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}